services:
  backend:
    build: ./backend
    container_name: task_master_backend
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:////data/sql_app.db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: task_master_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
